{ __nixpkgs_path }:
[
  ./config/ldso.nix
  ./config/nix-channel.nix
  ./config/nix-flakes.nix
  ./config/nix-remote-build.nix
  ./config/nix.nix
  ./config/nsswitch.nix
  ./config/shells-environment.nix
  ./config/system-path.nix
  ./config/terminfo.nix
  ./config/unix-odbc-drivers.nix
  ./config/users-groups.nix
  ./misc/assertions.nix
  ./misc/documentation.nix
  ./misc/extra-arguments.nix
  # TODO: actually use IDs in users module
  ./misc/ids.nix
  ./misc/label.nix
  ./misc/lib.nix
  ./misc/man-db.nix
  ./misc/meta.nix
  ({ ... }: {
    _module.args = {
      inherit __nixpkgs_path;
    };
    imports = [
      ./misc/nixpkgs.nix
    ];
  })
  ./misc/nixpkgs-flake.nix
  ./misc/passthru.nix
  ./misc/version.nix
  ./system/build.nix
  ./system/top-level.nix
  ./system/container.nix
  ./system/etc.nix
  ./system/nix2container.nix
  ./system/nix-snapshotter.nix
  ./system/nix.nix
  ./programs/shadow.nix
  ./security/pam.nix
  ./security/sudo.nix
  ./security/wrappers/default.nix
  ./programs/bash-my-aws.nix
  ./programs/bash/bash.nix
  ./programs/bash/bash-completion.nix
  ./programs/bash/ls-colors.nix
  ./programs/bash/blesh.nix
  ./programs/bash/undistract-me.nix
  ./programs/bat.nix
  ./programs/command-not-found/command-not-found.nix
  ./programs/direnv.nix
  ./programs/fish.nix
  ./programs/fzf.nix
  ./programs/git-worktree-switcher.nix
  ./programs/git.nix
  ./programs/htop.nix
  ./programs/lazygit.nix
  ./programs/less.nix
  ./programs/nano.nix
  ./programs/neovim.nix
  ./programs/nix-ld.nix
  ./programs/starship.nix
  ./programs/vim.nix
  ./programs/xonsh.nix
  ./programs/zsh/oh-my-zsh.nix
  ./programs/zsh/zsh-autoenv.nix
  ./programs/zsh/zsh-autosuggestions.nix
  ./programs/zsh/zsh-syntax-highlighting.nix
  ./programs/zsh/zsh.nix
  ./security/ca.nix
]
