AC_INIT([mode2octal], [0])
AC_CONFIG_AUX_DIR([build-aux])
AC_CONFIG_SRCDIR([mode2octal.c])
AM_INIT_AUTOMAKE

AC_CONFIG_HEADERS([config.h])

AC_PROG_CC

gl_EARLY
gl_INIT

AC_CONFIG_FILES([Makefile])
AC_CONFIG_FILES([m4/Makefile])
AC_CONFIG_FILES([lib/Makefile])
AC_CONFIG_FILES([tests/Makefile])

AC_OUTPUT
